# Generated by Django 5.2.4 on 2025-08-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=9)),
                ('salary', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
